
services:
  queue:
    image: redis:8.6.2
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  db:
    image: postgres:18.3
    container_name: postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
      # POSTGRES_USER: ${POSTGRES_USER}  
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      # POSTGRES_DB: ${POSTGRES_DB} 
      PGDATA: /var/lib/postgresql/data/pgdata    
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  # store:
  #   container_name: store
  #   build: .
  #   # network_mode: host
  #   # ports:
  #   #   - 8004:8000
  #   command: python3 main_test.py
  #   # command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload
  #   # volumes:
  #   #   - ./project:/usr/src/app
  #   env_file: ".env"
  #   # # environment:
  #   # #   - CELERY_BROKER_URL=redis://redis:6379/0
  #   # #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   network_mode: host
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: project
  #         target: /app/project
  #       - action: sync+restart
  #         path: main_test.py
  #         target: /app/main_test.py
  #       - action: rebuild
  #         path: requirements.txt
  worker:
    container_name: worker
    build: .
    # network_mode: host
    # ports:
    #   - 8004:8000
    command: faststream run project.auth_worker:app
    # command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload
    # volumes:
    #   - ./project:/usr/src/app
    env_file: ".env"
    # # environment:
    # #   - CELERY_BROKER_URL=redis://redis:6379/0
    # #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    network_mode: host
    develop:
      watch:
        - action: sync+restart
          path: project
          target: /app/project
        - action: rebuild
          path: requirements.txt
    # depends_on:
    #   - redis
    depends_on:
      queue:
        condition: service_healthy
  # store:
  #   container_name: store
  #   build: .
  #   # network_mode: host
  #   # ports:
  #   #   - 8004:8000
  #   command: python3 main_test.py
  #   # command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload
  #   # volumes:
  #   #   - ./project:/usr/src/app
  #   env_file: ".env"
  #   # # environment:
  #   # #   - CELERY_BROKER_URL=redis://redis:6379/0
  #   # #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   network_mode: host
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: project
  #         target: /app/project
  #       - action: rebuild
  #         path: requirements.txt
  auth_api:
    container_name: auth_api
    build: .
    # network_mode: host
    # ports:
    #   - 8004:8000
    # command: faststream run project.auth_api:app
    command: uvicorn project.auth_api:app --host 0.0.0.0 --port "${AUTH_API_PORT}"
    # command: uvicorn project.auth_api:app --host 0.0.0.0 --reload
    # volumes:
    #   - ./project:/usr/src/app
    env_file: ".env"
    # # environment:
    # #   - CELERY_BROKER_URL=redis://redis:6379/0
    # #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    network_mode: host
    develop:
      watch:
        - action: sync+restart
          path: project
          target: /app/project
        - action: rebuild
          path: requirements.txt
    depends_on:
      - worker
      # - queue:
      #     condition: service_healthy

  # worker:
  #   container_name: worker
  #   build: ./project
  #   command: celery -A selery_app.app:app worker --loglevel=info --logfile=logs/celery.log -P gevent
  #   volumes:
  #     - ./project:/usr/src/app
  #   env_file: ".env"
  #   # environment:
  #   #   - CELERY_BROKER_URL=redis://redis:6379/0
  #   #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   network_mode: host
  #   depends_on:
  #     - redis

  # beat:
  #   container_name: beat
  #   build: ./project
  #   command: celery -A selery_app.app:app beat --loglevel=info --logfile=logs/beat.log
  #   volumes:
  #     - ./project:/usr/src/app
  #   env_file: ".env"
  #   # environment:
  #   #   - CELERY_BROKER_URL=redis://redis:6379/0
  #   #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   network_mode: host
  #   depends_on:
  #     - redis
  #     - worker
      
  # dashboard:
  #   build: ./project
  #   command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
  #   network_mode: host
  #   # ports:
  #   #   - 5556:5555
  #   env_file: ".env"
  #   # environment:
  #   #   - CELERY_BROKER_URL=redis://redis:6379/0
  #   #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - redis
  #     - worker
  #     - beat

  # redis:
  #   image: redis:latest
  #   container_name: redis

volumes:
  pgdata:
    driver: local