"""Add cascade delete to user-permissions relationships

Revision ID: 361386f813d3
Revises: ee11472fd428
Create Date: 2026-05-06 15:38:29.883338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361386f813d3'
down_revision: Union[str, Sequence[str], None] = 'ee11472fd428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_permissions_association_table_permission_id_fkey'), 'users_permissions_association_table', type_='foreignkey')
    op.drop_constraint(op.f('users_permissions_association_table_user_id_fkey'), 'users_permissions_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'users_permissions_association_table', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_permissions_association_table', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_permissions_association_table', type_='foreignkey')
    op.drop_constraint(None, 'users_permissions_association_table', type_='foreignkey')
    op.create_foreign_key(op.f('users_permissions_association_table_user_id_fkey'), 'users_permissions_association_table', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('users_permissions_association_table_permission_id_fkey'), 'users_permissions_association_table', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###
