"""Change CartItems

Revision ID: 3d63288279b8
Revises: 3a4405c941e3
Create Date: 2026-05-16 13:41:09.616445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d63288279b8'
down_revision: Union[str, Sequence[str], None] = '3a4405c941e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('catr_itemms_cart_id_fkey'), 'catr_itemms', type_='foreignkey')
    op.drop_table('carts')
    op.add_column('catr_itemms', sa.Column('username', sa.String(), nullable=False))
    op.add_column('catr_itemms', sa.Column('nom_id', sa.Integer(), nullable=False))
    op.add_column('catr_itemms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('catr_itemms', 'cart_id')
    op.drop_column('catr_itemms', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catr_itemms', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catr_itemms', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('catr_itemms_cart_id_fkey'), 'catr_itemms', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('catr_itemms', 'quantity')
    op.drop_column('catr_itemms', 'nom_id')
    op.drop_column('catr_itemms', 'username')
    op.create_table('carts',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey')),
    sa.UniqueConstraint('username', name=op.f('carts_username_key'))
    )
    # ### end Alembic commands ###
