"""Add 'markup' to MNomenclature

Revision ID: 5bd45da0cd20
Revises: cba6aeea40fb
Create Date: 2026-05-11 17:14:59.922311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd45da0cd20'
down_revision: Union[str, Sequence[str], None] = 'cba6aeea40fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('markup', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomenclature', 'markup')
    # ### end Alembic commands ###
