"""Update User balanc to requared

Revision ID: 5c95e9a1979e
Revises: 9f2b7f7fd07f
Create Date: 2026-05-12 18:32:16.147447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from project.database.models import MUser


# revision identifiers, used by Alembic.
revision: str = '5c95e9a1979e'
down_revision: Union[str, Sequence[str], None] = '9f2b7f7fd07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.update(MUser).values({'balance': 0}))
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
