"""Add balance to User

Revision ID: 9f2b7f7fd07f
Revises: e0bd25fbda86
Create Date: 2026-05-12 18:29:36.129761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from project.database.models import MUser


# revision identifiers, used by Alembic.
revision: str = '9f2b7f7fd07f'
down_revision: Union[str, Sequence[str], None] = 'e0bd25fbda86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=True))
    # op.execute(sa.update(MUser).values({'balance': 0}))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
