"""Change socpe to permission

Revision ID: a1b08ff92cb7
Revises: 486f5f05f99e
Create Date: 2026-04-23 09:00:20.983508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b08ff92cb7'
down_revision: Union[str, Sequence[str], None] = '486f5f05f99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission')
    )
    op.add_column('association_table', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('association_table_scope_id_fkey'), 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'permission', ['permission_id'], ['id'])
    op.drop_column('association_table', 'scope_id')
    op.drop_table('scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_table', sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key(op.f('association_table_scope_id_fkey'), 'association_table', 'scope', ['scope_id'], ['id'])
    op.drop_column('association_table', 'permission_id')
    op.create_table('scope',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scope_pkey'))
    )
    op.drop_table('permission')
    # ### end Alembic commands ###
