"""Add created_at to MOrder

Revision ID: c827ffcb74e1
Revises: cf4de176b400
Create Date: 2026-05-29 07:49:52.266162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c827ffcb74e1'
down_revision: Union[str, Sequence[str], None] = 'cf4de176b400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')

    # ### end Alembic commands ###
