"""Update 'markup' to MNomenclature

Revision ID: e0bd25fbda86
Revises: 5bd45da0cd20
Create Date: 2026-05-11 17:47:44.229702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bd25fbda86'
down_revision: Union[str, Sequence[str], None] = '5bd45da0cd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomenclature', 'markup',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomenclature', 'markup',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
